### ISSUE TITLE
fontExists always returning false with custom fonts

### ISSUE THREAD

**Issue by francescocretti** [d3plus/d3plus-text#132]
As suggested by @davelandry in[ this comment ](https://github.com/d3plus/d3plus-react/issues/52#issuecomment-1135986103), I'm trying to use a custom font in a d3 Plus viz. 

I'm using `React v17`, `d3plus-react v1.2.1` and the viz is a Treemap.
I want both the labels in the chart and in the legend to have the same custom font.

Here's my (partial) configuration:

```javascript
const treemapConfig = {
  shapeConfig: {
    labelConfig: {
      fontFamily: 'Droid Sans Mono',
      fontWeight: 400
    }
  },
  legendConfig: {
    align: 'left',
    padding: 15,
    shapeConfig: {
      width: 20,
      height: 20,
      labelConfig: {
        fontSize: 13,
        fontFamily: 'Droid Sans Mono',
        fontWeight: 400
      },
    },
  },
};
```

that is just passed  to the component: `<Treemap config={treemapConfig} />`.

I obviously included the font files (`ttf`, `woff` and `woff2`) in my CSS:

```css
@font-face {
  font-family: 'Droid Sans Mono';
  src: url('../../../fonts/DroidSansMono-webfont.woff2') format('woff2'),
       url('../../../fonts/DroidSansMono-webfont.woff') format('woff'),
       url('../../../fonts/DroidSansMono-webfont.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}
```
I know the import is working because I can use the Droid Sans Mono font in other parts of my application without any issue.

However, something odd is happening: the font displayed is a serif font, but the spaces seem to be calculated as a monospace font (I attached a screenshot) and the `<text>` elements in the chart (and in the legend) have a `font-family: false` attribute.

So I dug a little bit in the source code and the problem is that the [`fontExists` ](https://github.com/d3plus/d3plus-text/blob/main/src/fontExists.js) method returns false.

After a couple of tests I noticed that the width of the test string `alpha = "abcdefghiABCDEFGHI_!@#$%^&*()_+1234567890"` calculated by `textWidth` method is the same for my font and for the default `monospace` font. This makes sense since they are both monospace fonts but this also make the [condition at line 32](textWidth) to return false and the method itself to return `false`. 

I also tried with a custom sans-serif font and I have the same behaviour but with the default `sans-serif` (aka `proportional`).

Am I missing something here?  :)

I am working on MacOS Monterey v12.6v with both Chrome v108.0.5359.124v and Firefox v108.0.2.

Thanks in advance for any help and thanks to the creators and maintainers of this tool, that remains awesome.

<img width="692" alt="Screenshot 2023-01-05 at 16 25 44" src="https://user-images.githubusercontent.com/11871906/211886731-467aa0a8-1e76-4439-9bad-67b2e5f65128.png">
